replicaCount: 1 # Only need 1 pod for testing

image:
  repository: fcog/ai-inference
  tag: "722dcf736036c8fc626caa666b2542815acadffa"
  pullPolicy: Always

resources:
  requests:
    cpu: "50m" # Tiny resource request to save money
  limits:
    cpu: "200m"
