# Default values for our AI microservice
replicaCount: 2

image:
  repository: fcog/ai-inference # Updated to your Docker Hub repo
  tag: "722dcf736036c8fc626caa666b2542815acadffa"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1000m" # Reserves full CPU cores (or GPUs)
  limits:
    cpu: "2000m"
