apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-processor-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-processor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-processor
    spec:
      containers:
      - name: processor-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10