replicaCount: 1 # Only need 1 pod for testing

image:
  repository: fcog/ai-inference
  tag: "75ee6a8ab578e12f0bdcdd669e3c3f46de73d7aa"
  pullPolicy: Always

resources:
  requests:
    cpu: "50m" # Tiny resource request to save money
  limits:
    cpu: "200m"
