replicaCount: 1 # Only need 1 pod for testing

image:
  repository: fcog/ai-inference
  tag: "4e9ba0a2dbfe75a5aad76bd9d3761cfbd4bf8877"
  pullPolicy: Always

resources:
  requests:
    cpu: "50m" # Tiny resource request to save money
  limits:
    cpu: "200m"
