# Default values for our AI microservice
replicaCount: 2

image:
  repository: fcog/ai-inference # Updated to your Docker Hub repo
  tag: "fbf1e23373080107710ed7def00344c35463cfe4"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1000m" # Reserves full CPU cores (or GPUs)
  limits:
    cpu: "2000m"
