# Default values for our AI microservice
replicaCount: 2

image:
  repository: fcog/ai-inference # Updated to your Docker Hub repo
  tag: "75ee6a8ab578e12f0bdcdd669e3c3f46de73d7aa"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1000m" # Reserves full CPU cores (or GPUs)
  limits:
    cpu: "2000m"
