# Default values for our AI microservice
replicaCount: 2

image:
  repository: fcog/ai-inference # Updated to your Docker Hub repo
  tag: "4e9ba0a2dbfe75a5aad76bd9d3761cfbd4bf8877"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1000m" # Reserves full CPU cores (or GPUs)
  limits:
    cpu: "2000m"
