replicaCount: 1 # Only need 1 pod for testing

image:
  repository: fcog/ai-inference
  tag: "fbf1e23373080107710ed7def00344c35463cfe4"
  pullPolicy: Always

resources:
  requests:
    cpu: "50m" # Tiny resource request to save money
  limits:
    cpu: "200m"
