apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: ai-service
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: ai-node-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
          env:
          # --- FETCHING FROM VAULT SECRET GENERATOR ---
          - name: AI_PROVIDER
            valueFrom:
              secretKeyRef:
                name: ai-app-runtime-secrets # Matches target.name in Step 3
                key: AI_PROVIDER          # Matches secretKey in Step 3          
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: ai-app-runtime-secrets 
                key: OPENAI_API_KEY 
          - name: ANTHROPIC_API_KEY
            valueFrom:
              secretKeyRef:
                name: ai-app-runtime-secrets 
                key: ANTHROPIC_API_KEY 
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: ai-app-runtime-secrets 
                key: REDIS_URL                                 
          # ---------------------------------------------
          # MLOps focus: Kubernetes monitors if your AI model crashes or locks up
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
