apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP # 🔒 Completely hides your Node.js app from the public network layer
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
